server:
  port: 8800
spring:
  security:
    user:
      name: admin
      password: admin-123
  application:
    name: sc-config-server
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin-123@localhost:8761/eureka/
