server:
  port: 8800
spring:
  security:
    user:
      name: admin
      password: admin-123
  application:
    name: sc-config-server
  cloud:
    config:
      server:
        git:
          bootstrap: true
          uri: https://github.com/ailijuan-2020/-StudyRepository.git
          username: ailijuan-2020
          password: ailijuan2020
          searchPaths: '{application}'
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin-123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: sc-config-server

